import { Button } from 'antd'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>“天选”-基于集成学习的航空旅客偏好预测系统</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.top}>
          <h1 className={styles.title}>
            <a>“天选” -</a> 基于集成学习的航空旅客偏好预测系统
          </h1>
          <div className={styles.top_right}>
            <Link href={'http://localhost:3000/'}>
              <Button className={styles.button} >系统首页</Button>
            </Link>
            <Link href={'http://localhost:3000/algorithm'}>
              <Button className={styles.button} >预测算法可视化展示</Button>
            </Link>
            <Link href={'http://localhost:3000/predict'}>
              <Button className={styles.button} >付费选座预测</Button>
            </Link>
            <Link href={'http://localhost:3000/history'}>
            <Button className={styles.button} >历史数据可视化展示</Button>
            </Link>
            <Link href={'http://localhost:3000/airplane-id'}>
              <Button className={styles.button} >航班查询</Button>
            </Link>
          </div>
        </div>
        
        <div className={styles["image-wrap"]}>
          <p className={styles.description}>
            随着我国航空运输网络不断完善，市场竞争逐渐激烈，服务质量是影响航空企业生存的关键因素。为了提升服务质量，把握客户资源，企业越来越关注旅客偏好。因此提取、预测旅客偏好，对于企业稳定旅客的增量和存量具有重要作用。通过本系统精准预测识别拥有付费意愿的旅客并实施精准营销，能够在耗费较低营销成本的情况下达到更满意的效果。
          </p>
        </div>
      </main>
    </div>
  )
}
