import { Button } from 'antd'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.top}>
          <h1 className={styles.title}>
            <a>“天选” -</a> 基于集成学习的航空旅客偏好预测系统
          </h1>
          <Button>系统首页</Button>
          <Button>付费选座预测</Button>
          <Button>历史数据可视化展示</Button>
          <Button>航班查询</Button>
        </div>
        
        <div className={styles["image-wrap"]}>
          <p className={styles.description}>
            Get started by editing{' '}
            {/* <code className={styles.code}>pages/index.js</code> */}
          </p>
        </div>

        
      </main>

    </div>
  )
}
